- include_vars: aws_credentials.yml

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
   - python-pip
  become: yes

- name: Install ansible modules
  become: yes
  pip: name={{ item }}
  with_items:
   - boto
   - python-jenkins
   - lxml

- name: Creating jenkins ec2 instance
  ec2:
   aws_access_key: "{{access_key}}"
   aws_secret_key: "{{secret_key}}"
   key_name: "{{kname}}"
   instance_type: "{{jenkins_instance_type}}"
   region: "{{region_name}}"
   image: "{{image_name}}"
   wait: yes
   groups: ['{{group_name1}}' , '{{group_name2}}']
   vpc_subnet_id: "{{vpc_subnet_id}}"
   assign_public_ip: yes
   wait_timeout: "{{wait_time}}"
   count: 1
   instance_tags:
    Name: Jenkins_Server
  register: jenkins_instance

- name: Creating app ec2 instances
  ec2:
   aws_access_key: "{{access_key}}"
   aws_secret_key: "{{secret_key}}"
   key_name: "{{kname}}"
   instance_type: "{{app_instance_type}}"
   region: "{{region_name}}"
   image: "{{image_name}}"
   wait: yes
   groups: ['{{group_name1}}' , '{{group_name2}}']
   vpc_subnet_id: "{{vpc_subnet_id}}"
   assign_public_ip: yes
   wait_timeout: "{{wait_time}}"
   count: "{{count}}"
   instance_tags:
    Name: "{{instance_name}}"
  register: ec2

- name: Adding host for Jenkins
  add_host:
   hostname: "{{jenkins_instance.instances[0].public_ip}}"
   groupname: jenkins
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Jenkins server IP address {{ jenkins_instance.instances[0].public_ip }}"


- name: Adding host for checkbox
  add_host:
   hostname: "{{ec2.instances[0].public_ip}}"
   ansible_host: "{{ec2.instances[0].public_ip}}"
   groupname: checkbox
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Checkbox server IP address {{ ec2.instances[0].public_ip }}"

- name: Adding host for checkbox
  add_host:
   hostname: "{{ec2.instances[1].public_ip}}"
   ansible_host: "{{ec2.instances[1].public_ip}}"
   groupname: checkbox
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Checkbox server IP address {{ ec2.instances[1].public_ip }}"

- name: Adding host for proxy server
  add_host:
   hostname: "{{ec2.instances[2].public_ip}}"
   ansible_host: "{{ec2.instances[2].public_ip}}"
   groupname: proxy
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Proxy server IP address {{ ec2.instances[2].public_ip }}"

- name: Adding host for iTrust
  add_host:
   hostname: "{{ec2.instances[3].public_ip}}"
   ansible_host: "{{ec2.instances[3].public_ip}}"
   groupname: iTrust
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Checkbox server IP address {{ ec2.instances[3].public_ip }}"

- local_action: file path={{project_path}}/hosts state=absent
  ignore_errors: yes
- local_action: file path=./hosts state=touch
- local_action: lineinfile line="[jenkins] \n{{jenkins_instance.instances[0].public_ip}} ansible_host={{ jenkins_instance.instances[0].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="[checkbox] \n{{ec2.instances[0].public_ip}} ansible_host={{ ec2.instances[0].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="{{ec2.instances[1].public_ip}} ansible_host={{ ec2.instances[1].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="[proxy] \n{{ec2.instances[2].public_ip}} ansible_host={{ ec2.instances[2].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="[iTrust] \n{{ec2.instances[3].public_ip}} ansible_host={{ ec2.instances[3].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts

- name: Waiting for port 22 to become available
  wait_for:
   host: "{{ item.public_dns_name }}"
   port: 22
   state: started
  with_items: "{{ jenkins_instance.instances }}"

- name: Waiting for port 22 to become available
  wait_for:
   host: "{{ item.public_dns_name }}"
   port: 22
   state: started
  with_items: "{{ ec2.instances }}"

- name: Accept new ssh fingerprints
  shell: ssh-keyscan -H {{ item.public_ip }} >> /home/ubuntu/.ssh/known_hosts
  with_items: '{{ jenkins_instance.instances }}'

- name: Accept new ssh fingerprints
  shell: ssh-keyscan -H {{ item.public_ip }} >> /home/ubuntu/.ssh/known_hosts
  with_items: '{{ ec2.instances }}'
