- include_vars: aws_credentials.yml

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
   - python-pip
  become: yes

- name: Install ansible modules
  become: yes
  pip: name={{ item }}
  with_items:
   - boto
   - python-jenkins
   - lxml

- name: Creating an ec2 instance
  ec2:
   aws_access_key: "{{access_key}}"
   aws_secret_key: "{{secret_key}}"
   key_name: "{{kname}}"
   instance_type: "{{instance_type}}"
   region: "{{region_name}}"
   image: "{{image_name}}"
   wait: "{{wait_var}}"
   groups: ['{{group_name1}}' , '{{group_name2}}']
   vpc_subnet_id: "{{vpc_subnet_id}}"
   assign_public_ip: "{{public_ip}}"
   wait_timeout: "{{wait_time}}"
   count: "{{count}}"
   instance_tags:
    Name: "{{instance_name}}"
  register: "{{aws_service}}"

- name: Adding host for Jenkins
  add_host:
   hostname: "{{ec2.instances[0].public_ip}}"
   groupname: jenkins
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Jenkins server IP address {{ ec2.instances[0].public_ip }}"

- name: Adding host for iTrust2
  add_host:
   hostname: "{{ec2.instances[1].public_ip}}"
   groupname: itrust
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "iTrust2 server IP address {{ ec2.instances[1].public_ip }}"

- name: Adding host for checkbox
  add_host:
   hostname: "{{ec2.instances[2].public_ip}}"
   groupname: checkbox
   ansible_ssh_user: ubuntu
   ansible_ssh_private_key_file: "{{project_path}}/ec2.key"
- debug:
   msg: "Checkbox server IP address {{ ec2.instances[2].public_ip }}"

- local_action: file path={{project_path}}/hosts state=absent
  ignore_errors: yes
- local_action: file path=./hosts state=touch
- local_action: lineinfile line="[jenkins] \nJenkins_Server ansible_host={{ ec2.instances[0].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="[itrust] \niTrust_Server ansible_host={{ ec2.instances[1].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts
- local_action: lineinfile line="[checkbox] \nCheckbox_Server ansible_host={{ ec2.instances[2].public_ip }} ansible_ssh_user=ubuntu ansible_ssh_private_key_file={{project_path}}/ec2.key" insertafter=EOF dest={{project_path}}/hosts


- name: Waiting for port 22 to become available
  wait_for:
   host: "{{ item.public_dns_name }}"
   port: 22
   state: started
  with_items: "{{ ec2.instances }}"

- name: Accept new ssh fingerprints
  shell: ssh-keyscan -H {{ item.public_ip }} >> /home/ubuntu/.ssh/known_hosts
  with_items: '{{ ec2.instances }}'
