- name: Install npm
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - nodejs-legacy
    - npm
    - make
    - build-essential
    - tcl8.5
    - gcc
    - libc6-dev
  become: yes

- name: download stable redis
  get_url: 
    url: http://download.redis.io/redis-stable.tar.gz
    dest: /tmp/redis-stable.tar.gz

- name: untar redis
  command: tar zxf /tmp/redis-stable.tar.gz -C /tmp

- name: Install binaries
  make:
    chdir: /tmp/redis-stable/
    target: install
  become: yes

- name: Comment out bind IP in redis.conf file
  replace: 
    path: /tmp/redis-stable/redis.conf
    regexp: '^bind'
    replace: '#bind'

- name: Change protected mode to no in redis.conf file
  replace:
    path: /tmp/redis-stable/redis.conf
    regexp: '^protected-mode yes'
    replace: 'protected-mode no'

- name: Ensure Redis is started 
  shell: "redis-server /tmp/redis-stable/redis.conf &"
  become: yes

- name: Install required packages
  npm:
    global: yes
    name: '{{ item }}'
  with_items:
    - forever
    - http
  become: yes

- name: Create proxy directory
  file:
    path: /home/ubuntu/Proxy
    state: directory
    mode: 0777
  become: yes

- name: Copy the package.json file
  template:
    src: package.json
    dest: "/home/ubuntu/Proxy/package.json"

- name: Copy the redis_server.json file
  template:
    src: redis_server.json.j2
    dest: "/home/ubuntu/Proxy/redis_server.json"

- name: Copy script to proxy server
  template:
    src: proxy.js
    dest: "/home/ubuntu/Proxy/proxy.js"

- name: Create the log file
  shell: touch /home/ubuntu/Proxy/log
 
