- name: Install required packages
  apt:
    pkg: '{{item}}'
    state: present
    update_cache: yes
  become: yes
  with_items:
    - nginx
    - mongodb
    - python3-pip
    - unzip

- name: Install Forever node package
  npm:
    name: forever
    state: present
    global: yes
  become: yes


- name: Install python package for mongodb
  pip:
    name: pymongo
    state: present
  become: yes

- name: Add a new mongodb user
  mongodb_user:
    database: admin
    name: "{{mongo_user}}"
    password: "{{mongo_password}}"
    state: present

- name: Restart mongoDb
  service:
   name: mongodb
   state: restarted
  become: yes

- name: Copy the checkbox config file
  template:
    src: checkbox_config.xml.j2
    dest: "{{project_path}}/roles/build_checkbox/templates/checkbox_config.xml"
  become: yes

- name: Fetch from jenkins server to local machine
  fetch:
    src: "{{project_path}}/roles/build_checkbox/templates/checkbox_config.xml"
    dest: "{{project_path}}/roles/build_checkbox/templates/"
    flat: yes

- jenkins_job:
   config: "{{ lookup('file', '../templates/checkbox_config.xml') }}"
   name: Checkbox_Build
   password: "{{jenkins_url_password}}"
   url: http://{{inventory_hostname}}:8080
   user: "{{jenkins_url_username}}"

- name: Involing checkbox build
  become: yes
  shell: "java -jar /tmp/jenkins-cli.jar -s http://{{inventory_hostname}}:8080/ build Checkbox_Build --username {{jenkins_url_username}} --password {{jenkins_url_password}} "
