- name: Install required packages
  apt:
    pkg: '{{item}}'
    state: present
    update_cache: yes
  become: yes
  with_items:
    - npm
    - nodejs
    - nodejs-legacy
    - nginx

- name: Ensuring previous clone isn't present
  file:
    state: absent
    path: '{{checkbox_app_path}}'

- name: Cloning Github repo
  git: repo=https://github.com/balaramesh/checkbox.io.git clone=yes dest={{checkbox_app_path}} version=canary

- name: Install Forever node package
  npm:
    name: forever
    state: present
    global: yes
  become: yes

- name: Install required node packages
  npm:
    path: "{{checkbox_app_path}}/server-side/site"

- name: Copy nginx.conf from repo /etc/nginx
  copy: remote_src=true src="{{checkbox_app_path}}/local-conf/nginx.conf" dest=/etc/nginx/nginx.conf
  become: yes

- name: Modify the server root in the default file
  replace:
    path: "{{checkbox_app_path}}/local-conf/default"
    regexp: "root (.)+;"
    replace: "root {{checkbox_app_path}}/public_html/;"

- name: Copy default file from repo to nginx folder
  copy: remote_src=true src="{{checkbox_app_path}}/local-conf/default" dest=/etc/nginx/sites-available/default
  become: yes

- name: Restart nginx
  service:
   name: nginx
   state: restarted
  become: yes

- name: Running server.js
  shell:  cd {{checkbox_app_path}}/server-side/site/; forever stopall; forever start server.js
  environment:
    MONGO_PORT: "{{mongo_port}}"
    MONGO_IP: "{{hostvars[groups['jenkins'][0]]['inventory_hostname'] }}"
    MONGO_USER: "{{mongo_user}}"
    MONGO_PASSWORD: "{{mongo_password}}"
    MAIL_USER: "{{mail_user}}"
    MAIL_PASSWORD: "{{mail_password}}"
    MAIL_SMTP: "{{mail_smtp}}"