- include_vars: mysql.yml
- include_vars: credentials.yml
- include_vars: paths.yml

- name: Stopping running instance of iTrust2 if already present
  shell: "ps -ef | grep jetty | grep -v grep | awk {'print $2'} | xargs kill -9"

- name: Install Git
  become: yes
  apt: pkg=git state=present update_cache=true cache_valid_time=1200

- name: Remove previous clone if present
  file:
    state: absent
    path: '{{iTrust_path}}'

- name: Cloning iTrust Github repo
  git:
    repo: https://{{ github_username | urlencode }}:{{ github_password}}@github.ncsu.edu/vmani2/iTrust2-v2.git
    clone: yes
    dest: "{{ home_path }}{{ iTrust_path }}"

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jdk

- name: Install Maven
  become: yes
  apt: pkg=maven state=present update_cache=true cache_valid_time=1200

- name: Create db.properties file from db.properties.template
  copy: remote_src=true src={{iTrust_path}}/iTrust2/src/main/java/db.properties.template dest="{{ home_path }}{{ iTrust_path }}/iTrust2/src/main/java/db.properties"

- name: Create hibernate.properties from hibernate.properties.template
  copy: remote_src=true src={{ iTrust_path}}/iTrust2/src/main/resources/hibernate.properties.template dest="{{ home_path }}{{ iTrust_path }}/iTrust2/src/main/resources/hibernate.properties"

- name: Copy hibernate.cfg.xml to src/main/resources/ folder
  copy: remote_src=true src={{iTrust_path}}/iTrust2/src/main/java/email.properties.template dest="{{ home_path }}{{ iTrust_path }}/iTrust2/src/main/java/email.properties"

- name: Replace {{root_password}} with the root_password variable
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/java/db.properties"
   regexp: 'password'
   replace: "password {{root_password}}"

- name: Replace localhost with the my_SQL IP
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/java/db.properties"
   regexp: 'localhost'
   replace: "{{hostvars[groups['jenkins'][0]]['inventory_hostname'] }}"

- name: Replace localhost with the my_SQL IP
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/resources/hibernate.properties"
   regexp: 'localhost'
   replace: "{{hostvars[groups['jenkins'][0]]['inventory_hostname'] }}"

- name: Replace {{root_db_password}} with the root_password variable
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/resources/hibernate.properties"
   regexp: 'hibernate.connection.password = '
   replace: "hibernate.connection.password = {{root_password}}"

- name: Replace from in email file
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/java/email.properties"
   regexp: 'from'
   replace: "from {{email_from}}"

- name: Replace email_id in email file
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/java/email.properties"
   regexp: 'username'
   replace: "username {{email_username}}"     

- name: Replace password in email file
  replace:
   path: "{{ iTrust_path }}/iTrust2/src/main/java/email.properties"
   regexp: 'password'
   replace: "password {{email_password}}"
     
- name: Starting the application
  shell: nohup mvn jetty:run &
  args:
   chdir: "{{ iTrust_path }}/iTrust2"

- name: Wait for application to come up
  wait_for:
   port: 8080